export const SHARED_ACTIONS = {
	PENDING_REQUEST: 'PENDING_REQUEST',
}

export const CATEGORY_ACTIONS = {
	REQUEST_CATEGORIES_SUCCESS: 'REQUEST_CATEGORIES_SUCCESS',
	REQUEST_CATEGORIES_ERROR: 	'REQUEST_CATEGORIES_ERROR'
}

export const SINGLEPOST_ACTIONS = {
	REQUEST_SINGLEPOST_SUCCESS: 'REQUEST_SINGLEPOST_SUCCESS',
	REQUEST_SINGLEPOST_ERROR: 	'REQUEST_SINGLEPOST_ERROR',
}