export const SHARED_ACTIONS = {
	PENDING_REQUEST: 'PENDING_REQUEST',
}

export const WP_CONTENT_ACTIONS = {
	REQUEST_WP_CONTENT_SUCCESS: 'REQUEST_WP_CONTENT_SUCCESS',
	REQUEST_WP_CONTENT_ERROR: 'REQUEST_WP_CONTENT_ERROR'
}

// export const CATEGORY_ACTIONS = {
// 	REQUEST_CATEGORIES_SUCCESS: 'REQUEST_CATEGORIES_SUCCESS',
// 	REQUEST_CATEGORIES_ERROR: 	'REQUEST_CATEGORIES_ERROR',
// }

export const POSTS_ACTIONS = {
	REQUEST_FILTERED_POSTS_SUCCESS: 'REQUEST_FILTERED_POSTS_SUCCESS',
	REQUEST_FILTERED_POSTS_ERROR: 'REQUEST_FILTERED_POSTS_ERROR', 
}

export const SINGLEPOST_ACTIONS = {
	REQUEST_SINGLEPOST_SUCCESS: 'REQUEST_SINGLEPOST_SUCCESS',
	REQUEST_SINGLEPOST_ERROR: 	'REQUEST_SINGLEPOST_ERROR',
}

export const SEARCH_ACTIONS = {
	REQUEST_SEARCH_VALUE_SUCCESS:'REQUEST_SEARCH_VALUE_SUCCESS', 
}